# Generated by Django 3.2 on 2022-02-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner_Country_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner_Region_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Region_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Partner_Region_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.partner_region')),
            ],
        ),
        migrations.CreateModel(
            name='RIS_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('Partner_Country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Partner_Region', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Sub_Region', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Modalities', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Sub_Modalities', models.CharField(default='', max_length=100)),
                ('No_of_Slots_Utilized', models.IntegerField(blank=True, default=0)),
                ('Disbursement_of_development_assistance_USD_million', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('Commitment_of_development_assistance_USD_million', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('Code_of_Sub_Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RISDatabase.sub_region')),
                ('Partner_Country_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RISDatabase.partner_country')),
                ('Partner_Region_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RISDatabase.partner_region')),
            ],
            options={
                'verbose_name': 'RIS Database',
            },
        ),
        migrations.AddField(
            model_name='partner_country',
            name='Partner_Region_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.partner_region'),
        ),
        migrations.AddField(
            model_name='partner_country',
            name='Sub_Region_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.sub_region'),
        ),
    ]
