# Generated by Django 3.2.12 on 2022-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISDatabase', '0002_alter_ris_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ris_project',
            name='Commitment_of_development_assistance_Rs',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Commitment_of_development_assistance_Rs_Crore',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Commitment_of_development_assistance_USD',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Commitment_of_development_assistance_USD_million',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Disbursement_of_development_assistance_Rs',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Disbursement_of_development_assistance_Rs_Crore',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Disbursement_of_development_assistance_USD',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Disbursement_of_development_assistance_USD_million',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='ris_project',
            name='Exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True),
        ),
    ]
