# Generated by Django 3.2 on 2022-02-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RISDatabase', '0003_auto_20220214_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner_country',
            name='Partner_Country_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner_country',
            name='Partner_Region_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.partner_region'),
        ),
        migrations.AlterField(
            model_name='partner_country',
            name='Sub_Region_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.sub_region'),
        ),
        migrations.AlterField(
            model_name='partner_region',
            name='Partner_Region_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_region',
            name='Partner_Region_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISDatabase.partner_region'),
        ),
        migrations.AlterField(
            model_name='sub_region',
            name='Sub_Region_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
